search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "directory"
workspaces = true
style = "compact"
inline_height = 40
inline_height_shell_up_key_binding = 40
invert = false
show_preview = true
max_preview_height = 6

enter_accept = false
command_chaining = true

sync_address = "https://api.atuin.sh"
auto_sync = true
sync_frequency = "10m"
update_check = true

[search]
filters = ["global", "workspace", "directory", "host", "session"]

[preview]
strategy = "auto"

[ui]
columns = ["time", "directory", "command"]

[sync]
records = true

[theme]
name = "catppuccin-macchiato-blue"

[daemon]

[stats]
common_subcommands = [
  "paru",
  "pacman",
  "systemctl",
  "journalctl",
  "git",
  "gh",
  "chezmoi",
  "hyprctl",
  "atuin",
  "nvim",
  "cargo",
  "npm",
  "pnpm",
]

common_prefix = ["sudo"]

[tmux]
enabled = true
width = "80%"
height = "60%"

[ai]
enabled = true
