#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

disable_root: true
ssh_pwauth: false
timezone: Europe/Amsterdam
users:
  - name: sander
    groups:
      - users
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

runcmd:
  - sudo -u sander -H sh -c 'curl -fsSL https://mise.run | sh'
  - sudo -u sander -H /home/sander/.local/bin/mise --version
  - sudo -u sander -H /home/sander/.local/bin/mise bootstrap --from https://github.com/SanderSpiegelaar/mise-bootstrap.git --update --yes
