#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

disable_root: true
ssh_pwauth: false
timezone: Europe/Amsterdam

users:
  - name: sander
    groups:
      - users
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINNjFhghHAGi7Y6BJu9RxQWHNUChrVD81EfnHxAfZRqX hetzner

runcmd:
  - |
    set -eu
    sudo -u sander -H sh -c 'curl -fsSL https://mise.run | sh'
    sudo -u sander -H /home/sander/.local/bin/mise bootstrap \
      --env linux \
      --from https://github.com/SanderSpiegelaar/mise-bootstrap.git \
      --update \
      --yes
