[tools]
tree-sitter = "latest":::qqiIIatuin = "latest"
bat = "latest"
bun = "latest"
codex = "latest"
curlie = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
node = "26"
nvim = "latest"
procs = "latest"
ripgrep = "latest"
starship = "latest"
superfile = "latest"
tmux = "latest"
topgrade = "latest"
usage = "latest"
zoxide = "latest"
