[tools]
"aqua:dalance/procs" = "latest"
atuin = "latest"
bat = "latest"
bun = "latest"
cargo-binstall = "latest"
codex = "latest"
curlie = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
neovim = "latest"
node = "26"
ripgrep = "latest"
starship = "latest"
superfile = "latest"
tealdeer = "latest"
tmux = "latest"
topgrade = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
