[dotfiles]
"
"~/.config/starship.toml" = "../../dotfiles/starship.toml"
"~/.config/eza" = "../../dotfiles/eza"
"~/.config/topgrade.toml" = "../../dotfiles/topgrade/topgrade.toml"
"~/.config/superfile" = "../../dotfiles/superfile"
"~/.config/nvim" = "../../dotfiles/nvim"
"~/.config/fish" = "../../dotfiles/fish"
"~/.config/atuin" = "../../dotfiles/atuin"
"~/.config/bat" = "../../dotfiles/bat"

## Sudo
[bootstrap.files."/etc/sudoers.d/sander"]
source = "../../files/sudoers/sander"
owner = "root"
group = "root"
mode = "0440"

## Docker
[bootstrap.directories."/etc/apt/keyrings"]
owner = "root"
group = "root"
mode = "0755"
phase = "pre-packages"

[bootstrap.files."/etc/apt/keyrings/docker.asc"]
source = "../../files/docker/docker.asc"
owner = "root"
group = "root"
mode = "0644"
phase = "pre-packages"

[bootstrap.files."/etc/apt/sources.list.d/docker.sources"]
source = "../../files/docker/docker.sources"
owner = "root"
group = "root"
mode = "0644"
phase = "pre-packages"

[bootstrap.files."/etc/docker/daemon.json"]
content = '{ "log-driver": "local" }'
notify = ["docker"]

## Fail2Ban
[bootstrap.files."/etc/fail2ban/jail.local"]
source = "../../files/fail2ban/jail.local"
owner = "root"
group = "root"
mode = "0644"
notify = ["fail2ban"]

## SSH
[bootstrap.files."/etc/ssh/sshd_config.d/99-hardening.conf"]
source = "../../files/ssh/99-hardening.conf"
owner = "root"
group = "root"
mode = "0644"

[bootstrap.files."/etc/sysctl.d/99-custom.conf"]
source = "../../files/sysctl/99-custom.conf"
owner = "root"
group = "root"
mode = "0644"
