[tasks.bootstrap]
description = "Finish user and system setup"
dir = "{{ config_root }}/../.."
run = [
  "fish scripts/install-fisher.fish",
  "git config --global user.name 'Sander'",
  "git config --global user.email 'sanderspiegelaar@gmail.com'",
  "tldr --update",
  "sudo sysctl --system",
  "sudo /usr/sbin/sshd -t && sudo systemctl reload ssh",
]
